( Vocabualaries )

VARIABLE VOC-LINK
: VOCABULARY ( -- )
    CREATE  CURRENT @ @ ,  HERE  VOC-LINK @ ,  VOC-LINK !
    DOES> @ CONTEXT ! ;

VOCABULARY FORTH
' FORTH >BODY CONSTANT FORTH-WORDLIST

8 CONSTANT #ORDER
: ALSO  CONTEXT DUP CELL+ [ #ORDER 1- CELLS ] LITERAL MOVE ;
: PREVIOUS  CONTEXT DUP CELL+ SWAP  [ #ORDER CELLS ] LITERAL MOVE ;
: ONLY  CONTEXT [ #ORDER CELLS ] LITERAL ERASE  FORTH ;
: DEFINITIONS  CONTEXT @ CURRENT ! ;

: ORDER  CONTEXT BEGIN DUP @ WHILE
        13 - .NAME 
    REPEAT DROP ;
